[profile.dev]
opt-level = 0

[package]
name = "rrrryoza"
version = "0.1.0"
edition = "2021"
description = "A fun game where you guess what number the computer has chosen."
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
cargo-watch = "8.5.3"
